### ISSUE TITLE
Missing editable content

### ISSUE THREAD

**Issue by LLxD** [ArticaDev/site-nupep#10]
Our client spotted some content that must be editable.

This includes:

- The text in the about us section (should be possible to insert photos too!):
![image](https://user-images.githubusercontent.com/48529975/195986714-d218ec86-44f3-40c5-ab24-19689647b595.png)

- The overall content in the research section:
![image](https://user-images.githubusercontent.com/48529975/195986734-97c9d780-058a-440f-af44-3c8d5c1126c9.png)

- The partners logos and URLs
![image](https://user-images.githubusercontent.com/48529975/195986750-024b0d32-38ea-4358-987b-014e5b30da9c.png)

- The contact info
![image](https://user-images.githubusercontent.com/48529975/195986762-05a5b9e7-4f6a-43ca-904a-f5dc288f3f58.png)
![image](https://user-images.githubusercontent.com/48529975/195986769-3b317cd9-71bc-4d7c-9249-b65cd3573b7a.png)

**Comment by MarcosNBJ** [comment]
PR #30 solved it for the remaining sections.
