### ISSUE TITLE
Criação de um novo cargo - Egressos

### ISSUE THREAD

**Issue by LLxD** [ArticaDev/site-nupep#67]
Egressos recebem uma informação nova:
- Ano de conclusão de curso

**Comment by MarcosNBJ** [comment]
PRs https://github.com/ArticaDev/site-nupep/pull/79 for frontend and https://github.com/ArticaDev/nupep-cms/pull/6 for Strapi

**Comment by LLxD** [comment]
Closing the issue since the PRs were merged
